task:
  freebsd_instance:
    image: freebsd-13-0-release-amd64

  name: "release-vs-ponyc-release-freebsd-13"

  os_configuration_script:
    - sysctl net.inet.tcp.keepinit=1000

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash gmake git
    - bash .ci-scripts/freebsd-13-install-release-pony-tools.bash

  test_script:
    - export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
    - gmake ci config=release

task:
  freebsd_instance:
    image: freebsd-13-0-release-amd64

  name: "debug-vs-ponyc-release-freebsd-13"

  os_configuration_script:
    - sysctl net.inet.tcp.keepinit=1000

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash gmake git
    - bash .ci-scripts/freebsd-13-install-release-pony-tools.bash

  test_script:
    - export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
    - gmake ci config=debug
