name: PR

on:
  pull_request:
    paths:
      - '**'
      - '!**/*.md'
      - '!**/*.yml'
      - '!**/*.yaml'
      - '.github/workflows/pr.yml'

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder-with-libressl-4.2.0:nightly
    steps:
      - uses: actions/checkout@v6.0.2
      - name: config=debug
        run: make ci config=debug ssl=libressl
      - name: config=release
        run: make ci config=release ssl=libressl
      - name: open/close stress test
        run: build/debug/open-close 1000000

  macos:
    name: MacOS
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6.0.2
      - name: install pony tools
        run: bash .ci-scripts/macOS-install-nightly-pony-tools.bash
      - name: configure networking
        run: bash .ci-scripts/macOS-configure-networking.bash
      - name: config=debug
        run: |
          export PATH=/Users/runner/.local/share/ponyup/bin/:$PATH
          make ci config=debug ssl=libressl
      - name: config=release
        run: |
          export PATH=/Users/runner/.local/share/ponyup/bin/:$PATH
          make ci config=release ssl=libressl
      - name: open/close stress test
        run: build/debug/open-close 250000

  windows:
    name: Windows
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: 7f452ee8e525ace2166b9612a718698b3890c35d
      - name: Tune Windows Networking
        run: .ci-scripts\windows-configure-networking.ps1
      - name: Install Pony tools (ponyc 0.60.0)
        run: |
          Invoke-WebRequest "https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/0.60.0/ponyc-x86-64-pc-windows-msvc.zip" -OutFile C:\ponyc.zip
          Expand-Archive -Force -Path C:\ponyc.zip -DestinationPath C:\ponyc
          Invoke-WebRequest "https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-pc-windows-msvc.zip" -OutFile C:\corral.zip
          Expand-Archive -Force -Path C:\corral.zip -DestinationPath C:\ponyc
      - name: cache SSL libs
        id: restore-libs
        uses: actions/cache@v5.0.3
        with:
          path: build/libs
          key: libs-windows-2025-${{ hashFiles('make.ps1') }}
      - name: build SSL libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: .\make.ps1 -Command libs 2>&1;
      - name: crash reproduction loop (issue #237)
        run: |
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          for ($i = 1; $i -le 100; $i++) {
            Write-Host "=== Run $i/100 ==="
            .\make.ps1 -Command test -Config Release 2>&1;
          }
