name: Stress tests

on:
  schedule:
    - cron: "30 6 * * *"

permissions:
  packages: read

jobs:
  x86_64-linux:
    runs-on: ubuntu-latest

    name: Linux
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder-with-libressl-4.2.0:release
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build
        run: make stress-tests config=debug ssl=libressl
      - name: Run
        run: build/debug/open-close 15000000
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  macos:
    runs-on: macos-26

    name: MacOS
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install pony tools
        run: bash .ci-scripts/macOS-install-release-pony-tools.bash
      - name: Configure networking
        run: bash .ci-scripts/macOS-configure-networking.bash
      - name: Build
        run: |
          export PATH=/Users/runner/.local/share/ponyup/bin/:$PATH
          make ci config=debug ssl=libressl
      - name: Run
        run: build/debug/open-close 3750000
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  windows:
    runs-on: windows-2025

    name: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Tune Windows Networking
        run: .ci-scripts\windows-configure-networking.ps1
      - name: Install Pony tools
        run: .ci-scripts\windows-install-pony-tools.ps1 releases
      - name: Cache LibreSSL libs
        id: cache-libressl
        uses: actions/cache@v5.0.3
        with:
          path: |
            ssl.lib
            crypto.lib
            tls.lib
          key: libressl-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.ci-scripts/windows-install-libressl.ps1') }}
      - name: Install LibreSSL
        if: steps.cache-libressl.outputs.cache-hit != 'true'
        run: .ci-scripts\windows-install-libressl.ps1
      - name: Build
        run: |
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\make.ps1 -Command stress-tests -Config Debug 2>&1;
      - name: Run
        run: |
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\build\debug\open-close 1500
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
