name: Update lib cache

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "update-lib-cache"

permissions:
  packages: read

jobs:
  windows:
    name: Windows
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v6.0.2
      - name: cache SSL libs
        id: restore-libs
        uses: actions/cache@v5.0.3
        with:
          path: |
            ssl.lib
            crypto.lib
            tls.lib
          key: rootlibs-windows-2025-${{ hashFiles('make.ps1') }}
      - name: build SSL libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: .\make.ps1 -Command libs  2>&1;
