name: Update lib cache

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "update-lib-cache"

permissions:
  packages: read

jobs:
  windows:
    name: Windows
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4.1.1
      - name: cache SSL libs
        id: restore-libs
        uses: actions/cache@v4
        with:
          path: build/libs
          key: libs-windows-2025-${{ hashFiles('make.ps1') }}
      - name: build SSL libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: .\make.ps1 -Command libs  2>&1;
